### PR TITLE
allow mapper to send string row keys to pilosa

### PR DESCRIPTION
**Pull request by travisturner**
This is incomplete, but I wanted to push this up and see if you have any concerns at this point.
I'm trying to leverage the PDK code as much as I can, but there are parts where it's pretty dependent on `uint64` keys, especially around translation. In the case where I want Pilosa to manage the translation (as opposed to an external `Translator` such as `MapTranslator`, I actually don't want `Translator.GetID` to be called at all.

(Also, there are a couple of places where I replaced `Frame` with `Field`. There are other instances that I did not change, but that's because they are currently part of the public API.

### CODE REVIEW

**Comment by travisturner** [comment]
In case it isn't clear, this implementation requires the `Translator` to be nil'd out like:
```
mapper := pdk.NewCollapsingMapper()
mapper.Translator = nil
```

**Comment by travisturner** [comment]
Although, now I'm realizing that having a nil `Translator` doesn't work with the way the collapsing mapper is handling `bool` fields. Hmm.

**Comment by travisturner** [comment]
I updated the `bool` case to use strings as well. At first I tried to create individual pilosa `bool` fields (as opposed to packing all `bool` attributes into the same field), but this seems to require modifying the `PilosaRecord` to effectively support `uint64OrStringOrBool`.

**Comment by jaffee** [comment]
this looks reasonable to me - lmk when it's out of WIP and I'll put the seal of approval on it

**Comment by travisturner** [comment]
@jaffee I added some tests and took this out of WIP.

**Pull request merged**
