### PR TITLE
conver from dep to go modules

### PR DESCRIPTION
**Pull request by jaffee**
OK module friends... what'd I screw up?

### CODE REVIEW

**Comment by codysoyland** [comment]
We shouldn't need vendor on any of the targets except gometalinter.

**Comment by jaffee** [comment]
docker wasn't a target, so I thought that meant it was useless to have it in the phony line. I assumed we removed the target a while ago and forgot to remove it from phony

**Comment by jaffee** [comment]
I wasn't sure why vendor had been removed from most targets in Pilosa. Now I understand that the only reason we're still vendoring is for tools that need it like gml

**Comment by jaffee** [comment]
ok @codysoyland @seebs I removed vendor from everything except gometalinter, and I removed everything in PHONY that wasn't a target in the Makefile.

**Pull request merged**
