### PR TITLE
Adds license header to missing files

### PR DESCRIPTION
**Pull request by yuce**

### CODE REVIEW

**Comment by travisturner** [comment]
This looks good, however two of the files have a build tag above the license header.
I don't think it matters, but usually we put build tags below the header, right @codysoyland?

**Comment by travisturner** [comment]
files with build tags:
```aws/s3/s3_test.go
kafka/integration_test.go```

**Comment by yuce** [comment]
No, the build tags should be above the license header. If you run `make test` and `make test-all` the outcomes will be differnet. Btw, it's the same in Go Pilosa.

**Comment by travisturner** [comment]
I asked because that's not the way we did it in the main pilosa repo. Either way, we should be consistent across our repos.

**Comment by yuce** [comment]
It seems build tags should be above the `package` name, doesn't need to be at the top of the file. Moved the build tags below the copyright header.

**Pull request merged**
